amcl:
  ros__parameters:
    # ----------------------
    # 基础配置
    # ----------------------
    use_sim_time: False              # 是否使用 ROS 模拟时间（False：使用真实硬件时间）
    base_frame_id: "base_link"       # 机器人基坐标系（需与 URDF 中定义一致）
    global_frame_id: "map"           # 全局地图坐标系
    odom_frame_id: "odom"            # 里程计坐标系
    tf_broadcast: true               # 是否广播 AMCL 估算的位姿变换
    transform_tolerance: 0.5         # TF 变换超时时间（秒），超过则认为定位失效

    # ----------------------
    # 粒子滤波核心参数
    # ----------------------
    max_particles: 5000              # 最大粒子数（粒子越多定位越稳定，但计算量越大）
    min_particles: 1000               # 最小粒子数（低于此值触发重采样）
    resample_interval: 1             # 重采样间隔（每累计 N 次更新后触发重采样）
    pf_z: 0.95                       # 重采样阈值（值越大，重采样越频繁）
    pf_err: 0.03                     # 收敛误差阈值（粒子分布误差低于此值时认为定位收敛）

    # ----------------------
    # 运动模型噪声参数（单位制：米/秒、弧度）
    # 描述里程计的不确定性，需根据机器人运动特性调整
    # ----------------------
    alpha1: 0.05                     # 旋转引起的旋转噪声（如编码器在旋转时的误差）
    alpha2: 0.05                     # 平移引起的旋转噪声（如平移时的方向漂移）
    alpha3: 0.05                     # 平移引起的平移噪声（平移距离误差）
    alpha4: 0.05                     # 旋转引起的平移噪声（旋转时的横向滑动）
    alpha5: 0.1                      # 系统偏差噪声（长期累积的系统性误差）

    # ----------------------
    # 激光雷达测量模型参数
    # ----------------------
    laser_model_type: "likelihood_field_prob"  # 激光匹配模型（概率场模型）
    laser_max_range: 6.0                       # 激光最大有效测量距离（米）
    laser_min_range: 0.01                      # 激光最小有效测量距离（米）
    laser_likelihood_max_dist: 3.0             # 激光与地图匹配的最大有效距离（米）
    max_beams: 600                             # 每次更新使用的激光束数量（减少可提升性能）

    # 测量模型权重（总和应接近 1.0）
    z_hit: 0.8                               # 激光击中障碍物的概率（有效测量权重）
    z_rand: 0.1                              # 随机噪声概率（激光误测为任意值的概率）
    z_short: 0.05                            # 短距离噪声概率（激光被小障碍物遮挡的概率）
    z_max: 0.05                              # 最大范围噪声概率（激光未检测到障碍物的概率）
    sigma_hit: 0.1                           # 测量噪声标准差（越小表示对激光数据越信任）
    scan_topic: scan
    
    # ----------------------
    # 光束跳过（Beam Skip）参数（用于过滤无效激光束）
    # ----------------------
    do_beamskip: false                       # 是否启用光束跳过（高精度地图建议关闭）
    beam_skip_threshold: 0.3                 # 光束强度阈值（低于此值的光束被跳过）
    beam_skip_error_threshold: 0.9           # 光束误差阈值（用于判断光束是否有效）
    beam_skip_distance: 0.5                  # 跳过光束的最小距离（米）

    # ----------------------
    # 机器人运动模型类型
    # ----------------------
    # 原先的配置
    #robot_model_type: "nav2_amcl::DifferentialMotionModel"  # 差分驱动机器人模型
    # 其他可选模型："nav2_amcl::KinematicModel"（运动学模型）、"nav2_amcl::OmnidirectionalModel"（全向模型）
    # 修改为适用于阿克曼结构的运动模型
    robot_model_type: "nav2_amcl::DifferentialMotionModel"  # 原配置，适用于差速驱动
    #robot_model_type: "nav2_amcl::KinematicModel"             # 修改：适用于阿克曼结构

    # # 运动模型误差参数（可根据实际调整）
    # odom_alpha1: 0.1  # 旋转引起的旋转误差
    # odom_alpha2: 0.1  # 平移引起的旋转误差
    # odom_alpha3: 0.2  # 平移引起的平移误差
    # odom_alpha4: 0.1  # 旋转引起的平移误差
    #以上是新增的
    # ----------------------
    # 初始化与恢复参数
    # ----------------------
    set_initial_pose: True                   # 是否允许通过服务设置初始位姿
    initial_pose: 
      x: 0.0                                 # 初始 x 坐标（米）
      y: 0.0                                 # 初始 y 坐标（米）
      yaw: 0.0                               # 初始偏航角（弧度，0 为地图坐标系 x 轴正方向）

    # ----------------------
    # 动态重采样与恢复
    # ----------------------
    recovery_alpha_fast: 0.0                 # 快速恢复时的运动噪声增益（应对剧烈运动）
    recovery_alpha_slow: 0.0                 # 缓慢恢复时的运动噪声增益（应对小误差）
    lambda_short: 0.1                        # 短距离激光束的权重（用于动态障碍物处理）

    # ----------------------
    # 更新频率控制
    # ----------------------
    update_min_a: 0.3                        # 角度变化阈值（弧度），达到此值才更新定位
    update_min_d: 0.3                        # 距离变化阈值（米），达到此值才更新定位
    save_pose_rate: 0.5                      # 保存位姿的频率（Hz，0.5 表示每 2 秒保存一次）


